# Generated by Django 5.1.7 on 2025-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registro_ANS', models.CharField(max_length=200)),
                ('CNPJ', models.CharField(max_length=20)),
                ('Razao_Social', models.CharField(max_length=200)),
                ('Modalidade', models.CharField(max_length=100)),
                ('Logradouro', models.CharField(max_length=200)),
                ('Numero', models.CharField(max_length=20)),
                ('Complemento', models.CharField(max_length=100)),
                ('Bairro', models.CharField(max_length=80)),
                ('Cidade', models.CharField(max_length=80)),
                ('UF', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=8)),
                ('DDD', models.CharField(max_length=2)),
                ('Telefone', models.CharField(max_length=9)),
                ('Fax', models.CharField(max_length=8)),
                ('Endereco_eletronico', models.CharField(max_length=100)),
                ('Representante', models.CharField(max_length=150)),
                ('Cargo_Representante', models.CharField(max_length=80)),
                ('Regiao_de_Comercializacao', models.CharField(max_length=1)),
                ('Data_Registro_ANS', models.CharField(max_length=10)),
            ],
        ),
    ]
