# Generated by Django 5.1.7 on 2025-03-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadora',
            name='DDD',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='UF',
            field=models.CharField(max_length=20),
        ),
    ]
