# Generated by Django 5.1.7 on 2025-03-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadoras', '0002_alter_operadora_ddd_alter_operadora_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadora',
            name='Fax',
            field=models.CharField(max_length=20),
        ),
    ]
