# Generated by Django 5.1.7 on 2025-03-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadoras', '0003_alter_operadora_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadora',
            name='CEP',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='Regiao_de_Comercializacao',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='Telefone',
            field=models.CharField(max_length=20),
        ),
    ]
