# Generated by Django 5.1.7 on 2025-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadoras', '0004_alter_operadora_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadora',
            name='Bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='CEP',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='CNPJ',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='Cargo_Representante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='DDD',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='Data_Registro_ANS',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='Fax',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='Regiao_de_Comercializacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='Telefone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='UF',
            field=models.CharField(max_length=100),
        ),
    ]
